export const GOOGLE_SEARCH_PRICE = 5 / 1000;
export const GEMINI_FLASH_INPUT_LOW_PRICE = 0.075;
export const GEMINI_FLASH_INPUT_HIGH_PRICE = 0.15;
export const GEMINI_FLASH_OUTPUT_LOW_PRICE = 0.3;
export const GEMINI_FLASH_OUTPUT_HIGH_PRICE = 0.6;
export const GEMINI_HILO_BOUNDARY = 128000;

export const GPT4O_MINI_INPUT_PRICE = 0.15;
export const GPT4O_MINI_OUTPUT_PRICE = 0.3;
export const GPT4O_INPUT_PRICE = 2.5;
export const GPT4O_OUTPUT_PRICE = 10;

export const ONEMILTOKENS = 1000000;

export const TRIGGER_INVOKE_COST = 0.000025;
export const TRIGGER_TIME_COST = 0.0000169;

